[project]
name = "breakfast-bar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "flask-mail>=0.10.0",
    "logging>=0.4.9.6",
    "pymysql>=1.1.2",
]
